docker:
  images_cache: "192.168.1.224/"
  confluence:
    server:
      ctnr_name: "confluence"
      image: "atlassian/confluence:latest"
      id: "BUVS-ZF5Y-WEH4-6WMN"
      ports:
        - "80:8090"
        - "81:8091"
    db:
      ctnr_name: "confluence-db"
      image: "postgres"
      name: "confluence-db"
      user: "confluence-dbuser"
      pwd: "confluence-dbpwd"
      ports:
        - "8060:5432"
