- name: Delete distant backup directory
  file:
    path: /tmp/backup/{{ inventory_hostname }}
    state: absent

- name: Create distant backup directory
  file:
    path: /tmp/backup/{{ inventory_hostname }}
    state: directory
    mode: '0700'

- include_tasks: backup-confluence.yml
- include_tasks: backup-jira.yml

- name: Create local backup directory
  file:
    path: ~/W/backup
    state: directory
    mode: '0750'
  delegate_to: localhost

- name: Retrieve files
  synchronize:
    mode: pull
    src: /tmp/backup
    dest: ~/W