- name: Start confluence database
  community.docker.docker_container:
    name: "{{docker.confluence.db.ctnr_name}}"
    image: "{{docker.images_cache + docker.confluence.db.image}}"
    ports: "{{docker.confluence.db.ports}}"
    state: started
    restart_policy: always
    env:
      POSTGRES_DB: "{{docker.confluence.db.name}}"
      POSTGRES_USER: "{{docker.confluence.db.user}}"
      POSTGRES_PASSWORD: "{{docker.confluence.db.pwd}}"

- name: Start confluence webapp
  community.docker.docker_container:
    name: "{{docker.confluence.server.ctnr_name}}"
    image: "{{docker.images_cache + docker.confluence.server.image}}"
    ports: "{{docker.confluence.server.ports}}"
    state: started
    restart_policy: always

- name: Wait a bit for cfg file to be created
  pause:
    seconds: 10

- name: Set server id
  community.docker.docker_container_exec:
    container: "{{docker.confluence.server.ctnr_name}}"
    command: "sed -i 's;<properties>;<properties><property name=\"confluence.setup.server.id\">{{docker.confluence.server.id}}</property>;' confluence.cfg.xml"

- name: Restart server
  community.docker.docker_container:
    name: "{{docker.confluence.server.ctnr_name}}"
    restart : true